language: node_js
node_js:
  - "iojs"
  - "10.13"

  env:
    - NODE_ENV=test
    global:
      - CC_TEST_REPORTER_ID=44dbbb02e79725901edd551157c725b5d39fb04ab2834133e51ed8d147f3f44d

script:  
  - npm install

after_script:  
  - npm run test