
language: node_js

script:  
  - npm install

after_script:  
  - npm run test

after_success:
  - coveralls
  
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  

