let users = [
  {
    id: 1, 
    firstname: "Princess",
    lastname: "Egbuna",
    othernames: "Ebube",
    email: 'boobae@gmail.com', 
    username: "boobae123",
    registered: '1999-6-15', 
    isAdmin: 'false',
    parcels: [
      {
        id: 1, 
        placedby: 1, 
        weigth: 4, 
        weigthmetric: 'kg', 
        sentOn: '1999-6-15', 
        deliveredOn: '1999-6-15', 
        status: "pending",
        fromaddress: 'Yaba', 
        destination: 'Ojuelegba',
        currentLocation: 'Ojuelegba',
      },
      {
        id: 2, 
        placedby: 1, 
        weigth: 4, 
        weigthmetric: 'kg', 
        sentOn: '1999-6-15', 
        deliveredOn: '1999-6-15', 
        status: "pending",
        fromaddress: 'Yaba', 
        destination: 'Ojuelegba',
        currentLocation: 'Ojuelegba',
      },
    ]
  },
  {
    id: 2, 
    firstname: "Ada",
    lastname: "Egbuna",
    othernames: "Nne",
    email: 'nne@gmail.com', 
    username: "ada123",
    registered: '1999-6-15', 
    isAdmin: 'false',
    parcels: [
      {
        id: 1, 
        placedby: 1, 
        weigth: 4, 
        weigthmetric: 'kg', 
        sentOn: '1999-6-15', 
        deliveredOn: '1999-6-15', 
        status: "pending",
        fromaddress: 'Yaba', 
        destination: 'Ojuelegba',
        currentLocation: 'Ojuelegba',
      },
      {
        id: 2, 
        placedby: 1, 
        weigth: 4, 
        weigthmetric: 'kg', 
        sentOn: '1999-6-15', 
        deliveredOn: '1999-6-15', 
        status: "pending",
        fromaddress: 'Yaba', 
        destination: 'Ojuelegba',
        currentLocation: 'Ojuelegba',
      },
    ]
  },
]

export default users